const actionTypes = {
  RECEIVE_POSTS: 'RECEIVE_POSTS',
  RECEIVE_MORE_POSTS: 'RECEIVE_MORE_POSTS',
  ADD_POST: 'ADD_POST',
  RECEIVE_POST: 'RECEIVE_POST',
  REMOVE_POST: 'REMOVE_POST',
  REMOVE_ALL_POSTS: 'REMOVE_ALL_POSTS',
  UPDATE_POST: 'UPDATE_POST',
  REPLACE_POST: 'REPLACE_POST',
}

export default actionTypes;